<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <PackageId>TtwSDK.Redux</PackageId>
    <Version>1.0.0</Version>
    <Authors>Terry Tw Chen</Authors>
    <Description>A lightweight Redux implementation for Blazor and Unity.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
